apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplayer-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplayer
  template:
    metadata:
      labels:
        app: multiplayer
    spec:
      containers:
        - name: multiplayer
          image: europe-west1-docker.pkg.dev/legendaryum/legend-docker/multiplayer
